### ISSUE TITLE
explore plaid - read comment

### ISSUE THREAD

**Issue by colbisaurusrex** [theagilezebra/bolster#6]

**Comment by Svinets** [comment]
plaid service - connect ( https://plaid.com/products/connect/#how-it-works )
/connect endpoint to receive user-authorized transactions and account data

- plaid link provides the interface with which users with input their username and password (unique to institutions)
- on a successful interaction between plaid and the user's financial institution, plaid link provides us with a 'public_token', which we exchange for an 'access_token' through the exchange token endpoint (haven't gotten that far). and use the access_token to retrieve their account info
